# Generated by Django 5.1.6 on 2025-02-23 17:52

import feed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_rename_creted_at_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.CharField(blank=True, choices=[('Web Developement', 'Web Development'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('English', 'English'), ('History', 'History'), ('Geography', 'Geography'), ('Computer Science', 'Computer Science'), ('Arts', 'Arts'), ('Business', 'Business'), ('Health', 'Health'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=feed.models.postfile),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
