# Generated by Django 5.1.6 on 2025-02-23 18:57

import feed.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_alter_post_catagory_alter_post_img_alter_post_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.CharField(choices=[('Web Developement', 'Web Development'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('English', 'English'), ('History', 'History'), ('Geography', 'Geography'), ('Computer Science', 'Computer Science'), ('Arts', 'Arts'), ('Business', 'Business'), ('Health', 'Health'), ('Others', 'Others')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(null=True, upload_to=feed.models.postfile),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
