# Generated by Django 5.1.6 on 2025-02-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_alter_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='catagory',
            field=models.CharField(choices=[('Web Developement', 'Web Development'), ('Mathematics', 'Mathematics'), ('Science', 'Science'), ('English', 'English'), ('History', 'History'), ('Geography', 'Geography'), ('Computer Science', 'Computer Science'), ('Arts', 'Arts'), ('Business', 'Business'), ('Health', 'Health'), ('Others', 'Others')], max_length=100, null=True),
        ),
    ]
